INSERT INTO livro (isbn, titulo, numeroPaginas, edicao, precoVenda, formato, precoCusto, margemLucro, avaliacao, quantidadeEstoque, sinopse)
VALUES(9788551002490, "F*deu Geral", 288, 1, 27.92, "Brochura", 9.30, 18.62, 4.9, 100, "Vivemos em uma época interessante. Materialmente, nunca estivemos melhor - temos mais liberdade, mais saúde e mais riqueza do que em qualquer momento da história da humanidade. No entanto, tudo ao redor parece terrivelmente f*dido: aquecimento global, governantes horrorosos, economia em crise e todos constantemente ofendidos nas redes sociais. Temos acesso a tecnologia, educação e comunicação de maneiras que nossos ancestrais jamais sonhariam e, mesmo assim, sentimos essa desesperança esmagadora. O que está acontecendo, afinal? Se você também está se fazendo essa pergunta, o livro de Mark Manson é sua próxima leitura obrigatória. Em A sutil arte de ligar o f*da-se, Manson, de maneira brilhante, deu forma à ansiedade que permeia a vida moderna - agora, em F*deu geral, ele desvia seu olhar das falhas inevitáveis de cada indivíduo para as inúmeras calamidades que tomam o mundo. Ao trazer desde pesquisas psicológicas até pérolas da sabedoria atemporal de filósofos como Platão e Nietzsche (e Tom Waits), Manson disseca religião e política e trata de como as duas, desconfortavelmente, vieram a se assemelhar. Também explora nossa relação com o dinheiro, o entretenimento e a internet, e desafia de modo franco nossas definições de fé, felicidade, liberdade e, até mesmo, a própria definição de esperança. Um passeio inusitado e divertido pela dor em nossos corações e o estresse em nossas vidas.");

INSERT INTO livro (isbn, titulo, numeroPaginas, edicao, precoVenda, formato, precoCusto, margemLucro, avaliacao, quantidadeEstoque, sinopse)
VALUES(9788551002490, "A Sutil Arte de Ligar o F*da-se", 224, 1, 19.99, "Brochura", 9.30, 10.69, 4.4, 100, "Chega de tentar buscar um sucesso que só existe na sua cabeça. Chega de se torturar para pensar positivo enquanto sua vida vai ladeira abaixo. Chega de se sentir inferior por não ver o lado bom de estar no fundo do poço. Coaching, autoajuda, desenvolvimento pessoal, mentalização positiva — sem querer desprezar o valor de nada disso, a grande verdade é que às vezes nos sentimos quase sufocados diante da pressão infinita por parecermos otimistas o tempo todo. É um pecado social se deixar abater quando as coisas não vão bem. Ninguém pode fracassar simplesmente, sem aprender nada com isso. Não dá mais. É insuportável. E é aí que entra a revolucionária e sutil arte de ligar o foda-se. Mark Manson usa toda a sua sagacidade de escritor e seu olhar crítico para propor um novo caminho rumo a uma vida melhor, mais coerente com a realidade e consciente dos nossos limites. E ele faz isso da melhor maneira. Como um verdadeiro amigo, Mark se senta ao seu lado e diz, olhando nos seus olhos: você não é tão especial. Ele conta umas piadas aqui, dá uns exemplos inusitados ali, joga umas verdades na sua cara e pronto, você já se sente muito mais alerta e capaz de enfrentar esse mundo cão. Para os céticos e os descrentes, mas também para os amantes do gênero, enfim uma abordagem franca e inteligente que vai ajudar você a descobrir o que é realmente importante na sua vida, e f*da-se o resto. Livre-se agora da felicidade maquiada e superficial e abrace esta arte verdadeiramente transformadora");

INSERT INTO livro (isbn, titulo, numeroPaginas, edicao, precoVenda, formato, precoCusto, margemLucro, avaliacao, quantidadeEstoque, sinopse)
VALUES(9788595083653, "A Queda de Gondolin", 320, 1, 35.90, "Capa Dura", 10.20, 25.70, 4.8, 100, "O último dos três Grandes Contos Perdidos do legendário de J.R.R.Tolkien narra a jornada de Tuor rumo à cidade secreta de Gondolin, refúgio élfico do povo do Rei Turgon. Contra a bela cidade, levanta-se Morgoth, o Inimigo Sombrio, com seu exército de seres malévolos. A história da Queda de Gondolin começou a ser escrita em 1916 e agora ganha vida graças ao trabalho editorial de Christopher Tolkien, filho e executor legal das obras de Tolkien. Dessa forma cumprem-se duas sinas: a dos Elfos noldorin na Primeira Era do mundo e a do autor, ao conseguir publicar individualmente os três Grandes Contos dos Dias Antigos. Fechando a mitologia da Terra-média, A Queda de Gondolin, assim como Beren e Lúthien e Os Filhos de Húrin, foi ricamente ilustrada pelo renomado artista britânico Alan Lee, que retrata a fantasia de Tolkien há mais de 30 anos.");

INSERT INTO livro (isbn, titulo, numeroPaginas, edicao, precoVenda, formato, precoCusto, margemLucro, avaliacao, quantidadeEstoque, sinopse)
VALUES(9788556510761, "Fogo e Sangue", 664, 1, 41.00, "Brochura", 10.00, 31.00, 4.1, 100, "A arrebatadora história dos Targaryen ganha vida neste novo livro de George R.R. Martin, autor de As Crônicas de Gelo e Fogo, série que inspirou a adaptação de sucesso da HBO, “Game of Thrones”. Séculos antes dos eventos de A guerra dos tronos, a Casa Targaryen – única família de senhores dos dragões a sobreviver à Destruição de Valíria – tomou residência em Pedra do Dragão. A história de Fogo & Sangue começa com o lendário Aegon, o Conquistador, criador do Trono de Ferro, e segue narrando as gerações de Targaryen que lutaram para manter o assento, até a guerra civil que quase destruiu sua dinastia. O que realmente aconteceu durante a Dança dos Dragões? Por que era tão perigoso visitar Valíria depois da Destruição? Quais foram os piores crimes de Maegor, o Cruel? Essas são algumas das questões respondidas neste livro essencial, relatadas por um sábio meistre da Cidadela. Ricamente ilustrado com mais de oitenta imagens assinadas pelo artista Doug Wheatley, Fogo & Sangue dará aos leitores uma nova e completa visão da fascinante história de Westeros – um livro imperdível para os fãs do autor.");

INSERT INTO livro (isbn, titulo, numeroPaginas, edicao, precoVenda, formato, precoCusto, margemLucro, avaliacao, quantidadeEstoque, sinopse)
VALUES(9788551001288, "Mitologia Nordica", 288, 1, 27.50, "Capa Dura", 7.50, 20.00, 3.7, 100, "Quem, além de Neil Gaiman, poderia se tornar cúmplice dos deuses e usar de sua habilidade com as palavras para recontar as histórias dos mitos nórdicos? Fãs e leitores sabem que a mitologia nórdica sempre teve grande influência na obra do autor. Depois de servirem de inspiração para clássicos como Deuses americanos e Sandman, Gaiman agora investiga o universo dos mitos nórdicos. Em Mitologia nórdica, ele vai até a fonte dos mitos para criar sua própria versão, com o inconfundível estilo sagaz e inteligente que permeia toda a sua obra.Fascinado por essa mitologia desde a infância, o autor compôs uma coletânea de quinze contos que começa com a narração da origem do mundo e mostra a relação conturbada entre deuses, gigantes e anões, indo até o Ragnarök, o assustador cenário do apocalipse que vai levar ao fim no mundo. Às vezes intensos e sombrios, outras vezes divertidos e heroicos, os contos retratam tempos longínquos em que os feitos dos deuses eram contados ao redor da fogueira em noites frias e estreladas.Mitologia nórdica é o livro perfeito para quem quer descobrir mais sobre a mitologia escandinava e também para aqueles que desejam desvelar novas facetas dessas histórias.“Neil Gaiman é uma máquina humana de criar histórias.”Washington Post.");

INSERT INTO livro (isbn, titulo, numeroPaginas, edicao, precoVenda, formato, precoCusto, margemLucro, avaliacao, quantidadeEstoque, sinopse)
VALUES(9788551002933, "O Homem de Giz", 272, 1, 24.99, "Capa Dura", 4.99, 20.00, 4.0, 100, "Assassinato e sinais misteriosos em uma trama para fãs de Stranger Things e Stephen King Em 1986, Eddie e os amigos passam a maior parte dos dias andando de bicicleta pela pacata vizinhança em busca de aventuras. Os desenhos a giz são seu código secreto: homenzinhos rabiscados no asfalto; mensagens que só eles entendem. Mas um desenho misterioso leva o grupo de crianças até um corpo desmembrado e espalhado em um bosque. Depois disso, nada mais é como antes. Em 2016, Eddie se esforça para superar o passado, até que um dia ele e os amigos de infância recebem um mesmo aviso: o desenho de um homem de giz enforcado. Quando um dos amigos aparece morto, Eddie tem certeza de que precisa descobrir o que de fato aconteceu trinta anos atrás. Alternando habilidosamente entre presente e passado, O Homem de Giz traz o melhor do suspense: personagens maravilhosamente construídos, mistérios de prender o fôlego e reviravoltas que vão impressionar até os leitores mais escaldados.");
